# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0002_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='semester',
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
