# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0003_auto_20160119_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='department',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 16, 22, 318603, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='roll',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 16, 35, 978211, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='semester',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 16, 43, 468323, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 17, 13, 957040, tzinfo=utc), max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
