# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('introapp', '0005_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.AddField(
            model_name='signup',
            name='set_password',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 17, 59, 13, 744183, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
