# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0007_remove_signup_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 7, 46, 15, 473887, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
