# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0008_userprofile_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 7, 51, 29, 305681, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 7, 51, 37, 380044, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
