# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0009_auto_20160121_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.FloatField(max_length=5),
        ),
    ]
