# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0010_auto_20160121_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(58)]),
        ),
    ]
