# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0013_auto_20160121_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
